[build]
  # Build command
  command = "npm run build:prod"
  
  # Publish directory
  publish = "dist"
  
  # Build environment
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

[build.processing]
  # Skip processing for certain file types
  skip_processing = false

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"
    
    # PWA headers
    Service-Worker-Allowed = "/"

# Specific headers for assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# Service worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Manifest headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json"

# Robots.txt and sitemap
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"

# Environment-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    VITE_APP_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    VITE_APP_ENV = "staging"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_APP_ENV = "development"
